name: Publicar noticias en WordPress

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Se ejecuta todos los días a las 12:00 UTC

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo de log vacío (si no existe)
        run: |
          touch proceso_noticias.log

      - name: Verificar instalación de dependencias
        run: |
          pip freeze > installed_packages.txt
          if ! grep -Fxq "requests" installed_packages.txt || ! grep -Fxq "openai" installed_packages.txt; then
            echo "Error: Falta instalar dependencias requeridas." >&2
            exit 1
          fi

      - name: Ejecutar script de publicación
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python dogs_automatics_news.py || { echo "Error en el script de publicación." >> proceso_noticias.log; exit 1; }

      - name: Guardar logs como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: logs-publicacion
          path: proceso_noticias.log
          retention-days: 7