name: Publicar noticias en WordPress

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Se ejecuta todos los días a las 12:00 UTC

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Crear archivo de log vacío (si no existe)
        run: |
          touch proceso_noticias.log

      - name: Ejecutar script de publicación
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python publicar_noticias.py

      - name: Guardar logs como artefactos
        uses: actions/upload-artifact@v3
        with:
          name: logs-publicacion
          path: proceso_noticias.log
          retention-days: 7
